$('#Chad')
    .css('position', 'absolute')
    .css('top', '110px')
    .css('left', '50px')
    .fadeTo(3000, 1);
$('#ChadDesc')
    .hide()
    .css('position', 'absolute')
    .css('top', '150px')
    .css('left', '330px')
    .delay(2500)
    .show('slide', 2500);
$('#Chris')
    .delay(2000)
    .css('position', 'absolute')
    .css('top', '400px')
    .css('right', '50px')
    .fadeTo(3000, 1);
$('#ChrisDesc')
    .hide()
    .css('position', 'absolute')
    .css('top', '400px')
    .css('right', '300px')
    .css('text-align', 'right')
    .delay(4500)
    .show('slide', { direction: 'right' }, 2500);
$('#Dani')
    .hide()
    .css('position', 'absolute')
    .css('top', '600px')
    .css('left', '50px')
    .delay(6000)
    .fadeTo(3000, 1);
$('#DaniDesc')
     .hide()
    .css('position', 'absolute')
    .css('top', '600px')
    .css('left', '330px')
    .delay(6000)
    .show('slide', 2500);