$('#DO')
    .hide()
    .css('position', 'absolute')
    .css('top', '150px')
    .css('left', '25%')
    .delay(2500)
    .show('slide', 2500);
$('#WD')
    .hide()
    .css('position', 'absolute')
    .css('top', '347px')
    .css('right', '25%')
    .delay(2500)
    .show('slide', { direction: 'right' }, 2500);
$('#OM')
    .hide()
    .css('position', 'absolute')
    .css('top', '571px')
    .css('left', '25%')
    .delay(2500)
    .show('slide', 2500);