$('#macon')
    .css('position','absolute')
    .css('top', '118px')
    .css('right', '40%')
    .fadeTo(3000,1);
$('#maconDesc')
    .hide()
    .css('position','absolute')
    .css('top', '470px')
    .css('right', '25%')
    .delay(2500)
    .show('slide', 2500);
$('#glennville')
    .delay(2000)
    .css('position','absolute')
    .css('top','118px')
    .css('right','40%')
    .fadeTo(3000,1);
$('#glennvilleDesc')
    .hide()
    .css('position','absolute')
    .css('top','470px')
    .css('right','25%')
    .delay(4500)
    .show('slide', {direction: 'right'}, 2500);